enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  # TODO: Remove this once we upgrade to ESLint 8+
  "@typescript-eslint/utils@5.46.0":
    peerDependencies:
      typescript: "*"

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
  os:
    - darwin
    - linux
